# Generated by Django 3.1.3 on 2020-11-15 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_category_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
